server:
  port:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create
